// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: sys_authority/sys_authority.proto

package sys_authority

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Authority struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorityId   string `protobuf:"bytes,1,opt,name=AuthorityId,proto3" json:"AuthorityId,omitempty"`
	AuthorityName string `protobuf:"bytes,2,opt,name=AuthorityName,proto3" json:"AuthorityName,omitempty"`
	ParentId      string `protobuf:"bytes,3,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
}

func (x *Authority) Reset() {
	*x = Authority{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_authority_sys_authority_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authority) ProtoMessage() {}

func (x *Authority) ProtoReflect() protoreflect.Message {
	mi := &file_sys_authority_sys_authority_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authority.ProtoReflect.Descriptor instead.
func (*Authority) Descriptor() ([]byte, []int) {
	return file_sys_authority_sys_authority_proto_rawDescGZIP(), []int{0}
}

func (x *Authority) GetAuthorityId() string {
	if x != nil {
		return x.AuthorityId
	}
	return ""
}

func (x *Authority) GetAuthorityName() string {
	if x != nil {
		return x.AuthorityName
	}
	return ""
}

func (x *Authority) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

var File_sys_authority_sys_authority_proto protoreflect.FileDescriptor

var file_sys_authority_sys_authority_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x79, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x2f,
	0x73, 0x79, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x79, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x22, 0x6f, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12,
	0x20, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x12, 0x24, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x42, 0x4e, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x67, 0x65, 0x6f, 0x72, 0x67, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x6a, 0x69, 0x61,
	0x63, 0x68, 0x65, 0x6e, 0x67, 0x2f, 0x6d, 0x79, 0x2d, 0x73, 0x68, 0x6f, 0x70, 0x2d, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x79, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x3b, 0x73, 0x79, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sys_authority_sys_authority_proto_rawDescOnce sync.Once
	file_sys_authority_sys_authority_proto_rawDescData = file_sys_authority_sys_authority_proto_rawDesc
)

func file_sys_authority_sys_authority_proto_rawDescGZIP() []byte {
	file_sys_authority_sys_authority_proto_rawDescOnce.Do(func() {
		file_sys_authority_sys_authority_proto_rawDescData = protoimpl.X.CompressGZIP(file_sys_authority_sys_authority_proto_rawDescData)
	})
	return file_sys_authority_sys_authority_proto_rawDescData
}

var file_sys_authority_sys_authority_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sys_authority_sys_authority_proto_goTypes = []interface{}{
	(*Authority)(nil), // 0: sys_authority.Authority
}
var file_sys_authority_sys_authority_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sys_authority_sys_authority_proto_init() }
func file_sys_authority_sys_authority_proto_init() {
	if File_sys_authority_sys_authority_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sys_authority_sys_authority_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authority); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sys_authority_sys_authority_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sys_authority_sys_authority_proto_goTypes,
		DependencyIndexes: file_sys_authority_sys_authority_proto_depIdxs,
		MessageInfos:      file_sys_authority_sys_authority_proto_msgTypes,
	}.Build()
	File_sys_authority_sys_authority_proto = out.File
	file_sys_authority_sys_authority_proto_rawDesc = nil
	file_sys_authority_sys_authority_proto_goTypes = nil
	file_sys_authority_sys_authority_proto_depIdxs = nil
}
